Add a cache for the code generators
ssl-hep/ServiceX_frontend pull request #305
Opened 2023-09-06 18:40 UTC by prajwalkkumar

This commit adds functionality to cache the code generators for offline processing.

2023-09-14 17:05 UTC, BenGalewsky commented on servicex/app/codegen.py
> +    sx = ServiceXClient(url=url, backend=backend)
This should use the cache! I tried switching off wifi and this call didn't work

2023-09-14 17:11 UTC, BenGalewsky commented on servicex/app/codegen.py
> +def codegens(
This winds up with a weird command line
```
servicex codegen codegens --flush
```

Maybe 
```
servicex codegens flush
and 
servicex codegens list
```

2023-09-14 17:14 UTC, BenGalewsky requested changes
Weird CLI user experience - `servicex codegen codegens` doesn't make sense
I tried 
`servicex codegen codegens --flush`
then
` servicex codegen codegens` prints out 
```
Returning code generators from cache
```
They should not be in the cache at that point!

The examples are now working - try these out and make sure this all works as expected. Turn off your wifi and make sure you can get results out of cache if you are on an airplane

2023-09-15 20:24 UTC, prajwalkkumar commented on servicex/app/codegen.py
> +    sx = ServiceXClient(url=url, backend=backend)
This was using the cache. It works now with wifi off after some more changes.

2023-09-15 20:25 UTC, prajwalkkumar commented on servicex/app/codegen.py
> +def codegens(
This has the expected cli now. 
I moved it out of main.py and hence we were seeing this behaviour. 
servicex codegens flush
servicex codegens list work now

2023-09-15 20:25 UTC, prajwalkkumar commented
Made the changes requested!

2023-09-20 13:51 UTC, merged