Cache Clear fix on Temp files not deleting
ssl-hep/ServiceX_frontend pull request #343
Opened 2024-03-11 19:55 UTC by ketan96-m

### On windows the cache is set to `/tmp` - which causes bad things when you do cache clear #304

### Problem:
When user does not give `cache_path` in `.servicex`, the default temp directory is used. Therefore when you try to clear the cache, some files are not deleted due to permission issue.

### Fix:
Rather than having `/tmp` as the default added `/tmp/servicex_$USER`. 
This ensures the local cache is set to this path and it is safely deleted when clearing cache

### Code changes:
In the configuration.py-> `expand_cache_path(cls, v)`, changed the default value of `v="/tmp"` to `v="/tmp/servicex_$USER"`

Added tests for this new changes in test_config.py

2024-03-12 13:15 UTC, BenGalewsky requested changes
This looks great. I didn't know about the ${USER} interpolation and can't find it anywhere in a google search. I see that the test passes, so it must work, but it's a little surprising!
Can you do an [interactive rebase](https://medium.com/nona-web/cleaning-up-commit-history-with-git-rebase-61dc41d2829c) to eliminate your extra commits

2024-03-12 14:30 UTC, ketan96-m commented
The reason I used the ${USER} because inside the same function, a condition was present to replace this with the username of the system.
```
if "${USER}" in s_path and "UserName" in os.environ:
            s_path = s_path.replace("${USER}", os.environ["UserName"])
```

2024-03-13 21:43 UTC, ponyisi commented
Suggestion: if we keep the ${USER} interpolation (which I'm fairly neutral on) I suggest that instead of the environment variable logic, we switch to the standard library `os.getlogin` function (otherwise we are hard-coding assumptions about the client systems).

2024-03-15 14:18 UTC, BenGalewsky approved these changes
Thanks. this looks good and avoids an unexpected conflict in the tmp dir

2024-03-15 14:18 UTC, merged