Compatibility with python 3.12
ssl-hep/ServiceX_frontend pull request #345
Opened 2024-03-15 20:26 UTC by ketan96-m

Updated the pyproject.toml and test matrix in .github workflow ci.yaml file to allow python 3.12

### pyproject.toml 
```
[tool.poetry.dependencies]
python = "^3.8, **< 3.13**"
```
### .github/workflow/ci.yaml
test->strategy->matrix->python-version: `["3.8", "3.9", "3.10", "3.11", "3.12"]`

2024-03-18 21:15 UTC, matthewfeickert requested changes

2024-03-18 22:15 UTC, matthewfeickert commented on pyproject.toml
> +python = "^3.8, < 3.13"
https://github.com/ssl-hep/ServiceX_frontend/issues/346

2024-03-20 20:00 UTC, matthewfeickert commented on pyproject.toml
> +python = "^3.8, < 3.13"
Also related to https://github.com/iris-hep/analysis-systems-env-nightlies/pull/29

2024-03-22 19:26 UTC, BenGalewsky commented
Obsolete via #349

2024-03-22 19:26 UTC, closed without merging